### ISSUE TITLE
Anamnese - Criar Entidade e DTO

### ISSUE THREAD

**Issue by jean-mb** [orbitechz/NPVet-Backend#13]
Criar Entidade e DTO de Anamnese, seguindo o DER:

![Image](https://github.com/orbitechz/NPVet-Backend/assets/79486623/113e8ffe-06c5-4081-96f5-1f063bb9dffe)

Seria interessante fazer em conjunto das tasks de Pergunta #10 e Anamnese & Pergunta #12 por conta da relação Many-To-Many, **que nesse caso precisa existir uma Entidade para a tabela associativa**

@bouchraakl e @Piegat tem mais experiencia nesse caso

**Comment by bouchraakl** [comment]
Anamnese e AnamneseDTO implementadas.

**Comment by jean-mb** [comment]
Ok
